import cron from 'node-cron';
import fs from 'fs';
import path from 'path';
import { getDailyReportData } from './src/utils/salesLog.js';

const logDir = path.join(process.cwd(), 'logs');
const logFile = path.join(logDir, 'cron.log');
const WA_SERVER_URL = 'http://localhost:5180';
const OWNER_PHONE = process.env.OWNER_PHONE || '';

function sendDailyReport(triggerType) {
  const timestamp = new Date().toISOString();
  console.log(`[${timestamp}] Dispatching WhatsApp close report (${triggerType})...`);

  if (!fs.existsSync(logDir)) {
    fs.mkdirSync(logDir, { recursive: true });
  }
  
  const todayStr = new Date().toISOString().split('T')[0];
  
  // Get actual sales data from sales log
  const reportData = getDailyReportData(todayStr);
  
  // Format the WhatsApp message
  const message = formatDailyReportMessage(reportData, triggerType);
  
  // Send via WhatsApp server
  sendWhatsAppMessage(OWNER_PHONE, message)
    .then(response => {
      if (response.ok) {
        fs.appendFileSync(logFile, `${todayStr}|[${timestamp}] Report dispatched successfully via ${triggerType}.\n`);
        console.log('✅ Report execution completed - sent via WhatsApp');
      } else {
        fs.appendFileSync(logFile, `${todayStr}|[${timestamp}] Report dispatch failed: ${response.error}\n`);
        console.error('❌ Report dispatch failed:', response.error);
      }
    })
    .catch(error => {
      fs.appendFileSync(logFile, `${todayStr}|[${timestamp}] Report dispatch error: ${error.message}\n`);
      console.error('❌ Error sending report:', error);
    });
}

function formatDailyReportMessage(data, triggerType) {
  const { date, totals, hourlyBreakdown, topItems, salesCount } = data;
  
  const currentTime = new Date().toLocaleTimeString('en-IN', { 
    hour: '2-digit', 
    minute: '2-digit', 
    hour12: true 
  });
  
  // Format hourly breakdown
  const hours = Object.entries(hourlyBreakdown)
    .sort((a, b) => a[0] - b[0])
    .map(([hour, data]) => `${hour}:00 - ₹${data.total} (${data.count} bills)`)
    .join('\n');
  
  // Format top items
  const items = topItems
    .slice(0, 5)
    .map((item, i) => `${i + 1}. ${item.name} - ${item.count} sold`)
    .join('\n');
  
  return [
    '📊 *DAILY SALES REPORT — Mehfil-E-Nihari*',
    `📅 ${date}`,
    `⏰ ${currentTime}`,
    `🚀 Trigger: ${triggerType}`,
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '*💰 SALES SUMMARY*',
    `Total Sales: ₹${totals.totalSales.toLocaleString('en-IN')}`,
    `Total Bills: ${totals.billCount}`,
    `Total Items: ${totals.itemCount}`,
    '',
    '*💵 PAYMENT BREAKDOWN*',
    `Cash: ₹${totals.cashSales.toLocaleString('en-IN')}`,
    `UPI: ₹${totals.upiSales.toLocaleString('en-IN')}`,
    `Credit: ₹${totals.creditSales.toLocaleString('en-IN')}`,
    '',
    hours ? '*⏰ HOURLY BREAKDOWN*' : '',
    hours || '',
    '',
    items ? '*🍽️ TOP SELLING ITEMS*' : '',
    items || '',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━━',
    '_Auto-generated by Mehfil-E-Nihari POS_',
    '',
    '📱 Official App Download: https://drive.google.com/file/d/1sL9_Hari4tIWb9JfNEa-HojJpyBRiVg0/view?usp=sharing',
  ].filter(Boolean).join('\n');
}

async function sendWhatsAppMessage(phone, text) {
  if (!phone) {
    return { ok: false, error: 'No OWNER_PHONE configured' };
  }
  
  try {
    const response = await fetch(`${WA_SERVER_URL}/api/send`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ phone, text }),
    });
    
    const result = await response.json();
    return result;
  } catch (error) {
    return { ok: false, error: error.message };
  }
}

function checkMissedReport() {
  try {
    const todayStr = new Date().toISOString().split('T')[0];
    let alreadySent = false;

    if (fs.existsSync(logFile)) {
      const logs = fs.readFileSync(logFile, 'utf8');
      if (logs.includes(todayStr)) {
        alreadySent = true;
      }
    }

    const now = new Date();
    const currentHour = now.getHours();
    
    if (!alreadySent && currentHour < 12) {
      console.log('Missed report detected from yesterday due to shutdown. Catching up now...');
      sendDailyReport('Startup Catch-up');
    }
  } catch (error) {
    console.error('Error checking missed reports:', error);
  }
}

// Export initialization function for use in server.js
export function initializeWhatsAppCron() {
  checkMissedReport();

  cron.schedule('59 23 * * *', () => {
    sendDailyReport('Scheduled Cron');
  });

  console.log('WhatsApp cron background worker initialized. Waiting for triggers...');
}

// Only run the cron when this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  initializeWhatsAppCron();
}
