pluginManagement {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'ResturantBilling'

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}

include ':app'
includeBuild('../node_modules/@react-native/gradle-plugin')
